- name: Setup Lab Environment
  hosts: lab_servers
  remote_user: azureuser
  vars:
    n_users: 15

tasks:
  - linux_update:
    name: Update Linux
    command: sudo apt-get update
    sudo: true
    ignore_errors: true
    register: linux_update
    tags: linux_update

  - linux_upgrade:
    name: Upgrade Linux
    command: sudo apt-get upgrade -y
    sudo: true
    ignore_errors: true
    register: linux_upgrade
    tags: linux_upgrade

  - install_python:
    name: Install Python
    command: sudo apt-get install python -y
    sudo: true
    ignore_errors: true
    register: install_python
    tags: install_python

  - install_node:
    name: Install Node
    command: curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - && sudo apt-get install -y nodejs
    sudo: true
    ignore_errors: true
    register: install_node
    tags: install_node

  - install_node_dependencies:
    name: Install Node Dependencies
    command: sudo npm install -g configurable-http-proxy
    sudo: true
    ignore_errors: true
    register: install_node_dependencies
    tags: install_node_dependencies

  - install_jupyterhub:
    name: Install JupyterHub
    command: pip install jupyterlab jupyterhub
    sudo: true
    ignore_errors: true
    register: install_jupyterhub
    tags: install_jupyterhub

  - create_users:
    name: Create users
    user:
      name: "user{{ item }}"
      password: "user{{ item }}"
      groups: sudo
      append: yes
    with_sequence: start=1 end={{ n_users }}

  - start_jupyterhub:
    name: Start JupyterHub
    command: jupyterhub --ip 0.0.0.0 --port 443 --ssl-key {{ ssl_key_path }} --ssl-cert {{ ssl_cert_path }}

  # ansible task: install lets-encrypt package  and generate certificate
  - name: Install lets-encrypt package
    apt:
      name: letsencrypt
      state: present
    become: true

  #