- name: Setup Lab Environment
  hosts: lab_servers
  remote_user: azureuser
  vars:
    n_users: 3

  tasks:
    # ENVIRONMENT
    - name: Update and upgrade apt
      become: true  # become root, should replace sudo
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Python
      become: true
      apt:
        name: python3-pip
        state: present
      tags: python

    - name: Install node.js
      block:
      - apt:
          name:
            - apt-transport-https
            - gnupg2

      - apt_key:
          url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

      - apt_repository:
          repo: "{{ item }}"
          update_cache: yes
        loop:
          - >-
            deb https://deb.nodesource.com/node_19.x
            {{ ansible_distribution_release }} main
          - >-
            deb-src https://deb.nodesource.com/node_19.x
            {{ ansible_distribution_release }} main

      - apt:
          name: nodejs

      become: true
      tags: install_node

    - name: Install Jupyterhub
      block:
      - name: Install configurable-http-proxy
        become: true
        command: "npm install -g configurable-http-proxy"

      - name: Install JupyterHub Python package
        become: true
        command: pip3 install jupyterlab jupyterhub MarkupSafe==2.0.1
        ignore_errors: true
        register: install_jupyterhub
        tags: install_jupyterhub

    # TODO: install Python dependencies

    # - name: Checkout training repository from GitHub
    #   ansible.builtin.git:
    #     repo: "https://github.com/clstaudt/ai-training"
    #     dest: .


    # SETUP SSL
    - name: Setup SSL
      block:
      - name: Install snapd
        become: true
        apt:
          name: snapd
          state: present
      - name: Install certbot
        become: true
        command: snap install --classic certbot
      - name: Symlink certbot
        become: true
        file:
          src: /snap/bin/certbot
          dest: /usr/bin/certbot
          state: link

    # USER MANAGEMENT

    - name: Create users
      become: true
      user:
        name: "user{{ item }}"
        password: "user{{ item }}"
        groups: sudo
        append: yes
      with_sequence: start=1 end={{ n_users }}

    # START
    # TODO: probably Ansible is not made for starting processes, so this should go into a script

    # ansible task: start jupyterhub
    # - name: Start certbot 
    #   become: true
    #   shell: certbot certonly --standalone

    # - name: Start JupyterHub
    #   become: true
    #   ansible.builtin.shell: jupyterhub --ip 0.0.0.0 --port 443 --ssl-key {{ ssl_key }} --ssl-cert {{ssl_cert}} 